# Generated by Django 4.1.7 on 2023-03-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Twit_app', '0002_user_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
    ]
